name: Build Versioned Alpine Images

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Alpine:
    if: ${{ github.repository == 'swoole/php-docker' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4', '8.5', '8.1-zts', '8.2-zts', '8.3-zts', '8.4-zts', '8.5-zts']

    name: PHP-${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set output parameters
        id: params
        run: |
          echo "::set-output name=full_names::phpswoole/php:${{ matrix.php }}-alpine"

      - name: Build and push Docker image phpswoole/php:${{ matrix.php }}-alpine
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.php }}-alpine/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.params.outputs.full_names }}

      - name: Image digest of phpswoole/php:${{ matrix.php }}-alpine
        run: echo ${{ steps.docker_build.outputs.digest }}
